name: e2e test

on:
  push:
    paths:
      - "cypress/**"
      - "src/**"
      - ".github/workflows/e2e-test.yml"

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.16.1-chrome80-ff73
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0

      - name: Cypress run
        uses: cypress-io/github-action@v4.2.0
        with:
          start: npm run serve
          spec: cypress/e2e/*
