name: e2e test

on:
  push:
    paths:
      - "cypress/**"
      - "src/**"

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm run serve
          spec: cypress/integration/*
