name: unit test

on:
  push:
    paths:
      - "src/**"

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm ci || npm install

      - name: Run unit tests
        run: npm run test:unit
